server:
  port: 2408

spring:
  application:
    name: bigdata-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bigdata_dev_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

spark:
  spark-home: ${SPARK_HOME:/usr/bigdata/spark-3.5.8-bin-hadoop3}
  master: ${SPARK_MASTER:yarn}
  deploy-mode: ${SPARK_DEPLOY_MODE:cluster}
  hadoop-conf-dir: ${HADOOP_CONF_DIR:}
  yarn-staging-dir: /user/root/.sparkStaging/
