server:
  port: 12408

spring:
  application:
    name: bigdata-dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/bigdata_dev_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 2500MB
      max-request-size: 2500MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

spark:
  spark-home: ${SPARK_HOME:/usr/bigdata/spark-3.2.1-bin-hadoop3.2}
  master: ${SPARK_MASTER:yarn}
  deploy-mode: ${SPARK_DEPLOY_MODE:cluster}
  hadoop-conf-dir: ${HADOOP_CONF_DIR:/usr/bigdata/hadoop-3.2.0/etc/hadoop}
  yarn-staging-dir: /user/root/.sparkStaging/
  hive-site-xml: ${HIVE_SITE_XML:/usr/bigdata/apache-hive-3.1.2-bin/conf/hive-site.xml}
  fs-default-fs: ${FS_DEFAULT_FS:hdfs://linux001:9820}
  yarn-resource-manager-address: ${YARN_RM_ADDRESS:linux001:8032}
