version: "3.8"

services:
  linux001:
    build:
      context: ./bigdata-ubuntu  # 构建上下文目录
      dockerfile: Dockerfile     # 该目录下的 Dockerfile 文件名
    image: ubuntu-ssh
    container_name: linux001
    hostname: linux001
    networks:
      mynetwork:
        ipv4_address: 172.18.0.11
    extra_hosts:
      - "linux001:172.18.0.11"
      - "linux002:172.18.0.12"
      - "linux003:172.18.0.13"
      - "mysql:172.18.0.14"
    restart: unless-stopped

  linux002:
    image: ubuntu-ssh
    container_name: linux002
    hostname: linux002
    depends_on:
      - linux001
    networks:
      mynetwork:
        ipv4_address: 172.18.0.12
    extra_hosts:
      - "linux001:172.18.0.11"
      - "linux002:172.18.0.12"
      - "linux003:172.18.0.13"
      - "mysql:172.18.0.14"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g


  linux003:
    image: ubuntu-ssh
    container_name: linux003
    hostname: linux003
    depends_on:
      - linux001
    networks:
      mynetwork:
        ipv4_address: 172.18.0.13
    extra_hosts:
      - "linux001:172.18.0.11"
      - "linux002:172.18.0.12"
      - "linux003:172.18.0.13"
      - "mysql:172.18.0.14"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8g


  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.14
    extra_hosts:
      - "linux001:172.18.0.11"
      - "linux002:172.18.0.12"
      - "linux003:172.18.0.13"
      - "mysql:172.18.0.14"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d # 挂载初始化脚本目录，脚本一定要create database和use database，不然会no work
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g


  nginx:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "2408:80"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.15
    extra_hosts:
      - "linux001:172.18.0.11"
      - "linux002:172.18.0.12"
      - "linux003:172.18.0.13"
      - "mysql:172.18.0.14"
      - "backend:172.18.0.80"
    volumes:
      - ../bigdata-dev-ui/dist:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - linux001
      - mysql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g   

  springboot-tomcat:
    hostname: backend
    container_name: backend
    networks:
      mynetwork:
        ipv4_address: 172.18.0.80
    build:
      context: ./tomcat-service  # 构建上下文目录
      dockerfile: Dockerfile     # 该目录下的 Dockerfile 文件名
    # ports:
    #   - "8080:8080"              # 将容器的8080映射到主机的8080
    # 如果需要传递 JVM 参数
    extra_hosts:
      - "linux001:172.18.0.11"
      - "linux002:172.18.0.12"
      - "linux003:172.18.0.13"
      - "mysql:172.18.0.14"
      - "backend:172.18.0.80"
    environment:
      - JAVA_OPTS=-Xmx512m
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  mysql_data:
